spring.application.name=subsentry-api
spring.datasource.url=jdbc:mysql://localhost:3306/subsentry_db
spring.datasource.username=root
spring.datasource.password=MySQL25.com
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
subsentry.api.key=ddeeee4dfb1cc69baeaa72b2
